### PR TITLE
remove range_includes_special_ids validation

### PR DESCRIPTION
**Pull request by chrisns**
relates to #4

### CODE REVIEW

**Comment by viccuad** [comment]
Thanks! With the removal the unneeded tests are failing. Could you drop them too?

**Review by jvanz — COMMENTED** [review]
LGTM! As said by @viccuad , fix the tests and we can merge this.

**Comment by chrisns** [comment]
no idea what i'm doing, have removed some lines of code :) hopefully it works
theres some e2e tests but not sure what runs them?

**Comment by viccuad** [comment]
Argh, it's not passing rustfmt. To fix, run `cargo fmt`, and commit the results. It seems to be [just an excess newline](https://github.com/kubewarden/user-group-psp-policy/runs/4580903527?check_suite_focus=true#step:5:11)

On the topic of e2e-tests, they are normally run via Github Actions, with [bats-core](https://github.com/bats-core/bats-core) and [kwctl](https://github.com/kubewarden/kwctl). And indeed, there's no GHA workflow running them here. Since it's not a regression, we can fix it on a different PR. Opened https://github.com/kubewarden/policy-hub/issues/130 for that.

**Comment by viccuad** [comment]
I see that now is fixed! merging, Will update the e2e-tests in other PR, prior to release.

**Review by viccuad — APPROVED** [review]

**Pull request merged**
